<a href="https://colab.research.google.com/github/DSAishwaryaG/ANN/blob/main/Churn_Modelling(ANN_Classification).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project_Datasets/Churn_Modelling.csv')

**Data** **Preprocessing**

In [ ]:
x = data.iloc[:,3:-1].values #matrix of features
y = data.iloc[:,-1].values #target vector

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#Feature Scaling is very important and mandatory step in Deep Learning
#We have to scale all the features irrespective of columns which have values 0 and 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train) #object if fitted only to training set so as to avoid information leakage
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))#Dense class is used to create a fully connected neural network(input layer with 1st hiddenlayer)

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))#2nd hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))#output layer and sigmoid activation function is used as it not only gives better predictions 
                                                         #but also gives probabilities to be the predicted value
                                                         #sigmoid for binary output and softmax for 3 categorical output

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam optimiser perform stocastic gradient descent(updates the weights)
                                                                   #categorical_crossentropy for 3 categorical output and binary_crossentropy for binary output

In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)#batch_size is number of predictions in a batch to be compared to the same number of 
                                               #real results instead of one by one comparison
                                               #32 is default value of batch_size

Epoch 1/100
250/250 [==============================] - 4s 2ms/step - loss: 0.5178 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4714 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 0.7975
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4180 - accuracy: 0.8135
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3991 - accuracy: 0.8225
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3894 - accuracy: 0.8341
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3818 - accura

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))#predict must have a 2d array(double square brackets) as input either to predict either                                                   #of outcomes for ensemble of inputs or a single prediction
                                                  # ensemble fit gets mean and SD from the training set to transform the values using scalar so not need to fit 
                                                  #on test data and scaling is done because ann is trained on the scaled data
                                                  #0.024 says that customer leaving bank probability is less

[[0.02492201]]


In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)#False says that customer is not leaving the bank

[[False]]


In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)#less than 0.5 y_pred is False (0) and vice versa
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)#0.863 says that out of 100 customers 86 are predicted correctly to either stay in or leave the bank
                              #1523 correct predictions that customers stay in the bank
                              #203  correct predictions that customers leave the bank
                              #72 incorrect predictions that customers leave the bank
                              #202 incorrect predictions that customers stay in the bank

[[1523   72]
 [ 202  203]]


0.863