<a href="https://colab.research.google.com/github/DSAishwaryaG/ANN/blob/main/Power_Plant(ANN_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
data = pd.read_excel('/content/drive/MyDrive/Project_Datasets/Folds5x2_pp.xlsx')

In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [ ]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.2)
#random_state is the seed that will fix the randomness of train test split i.e to have same split everytime we execute

In [ ]:
#input layer contains features
#ann is of 2 types:Sequence of layers and Computational graph
#tensorflow is a deep learning library which helps to build complex neural networks and train them
#keras and tensorflow were separate before but after tensorflow 2, keras is combined with it
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))#no activation function for regression output

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')
#stocastic gradient descent(adam) is to update weights so as reduce the loss 
#mean_squared_error is used for regression 

In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)
#epochs is one pass of training set to the model(number of passes to reduce loss)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 632.7022
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 341.8712
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 270.8682
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 203.9564
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 150.1308
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 109.0273
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 80.2978
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 61.4451
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 50.2990
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 43.5263
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 40.5915
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 38.

In [ ]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)#    --rows----,columns                         
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))#reshape() reshapes horizontal to vertical
#                     ---------------2 vectors to concatenate---------------------- 1 for vertical concatenation
#                                                                                   0 for horizontal concatenation

[[432.07 431.23]
 [463.15 460.01]
 [466.66 461.14]
 ...
 [473.9  473.26]
 [440.62 438.  ]
 [459.86 463.28]]
